name: temppi_app
description: "A Temppi App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

# Dependencies
dependencies:
  flutter:
    sdk: flutter

  openapi:
    path: ./api

  flutter_riverpod: ^2.5.1
  cupertino_icons: ^1.0.8
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.2.0
  drag_and_drop_lists: ^0.4.1
  fl_chart: ^0.69.0
  multi_dropdown: ^3.0.1
  settings_ui: ^2.0.2
  flutter_launcher_icons: ^0.13.1
  form_validator: ^2.1.1
  flutter_datetime_picker_plus: ^2.2.0

# Dev depencencies
dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.2.1
  flutter_lints: ^4.0.0
  riverpod_generator: ^2.3.3
  custom_lint: ^0.6.5
  riverpod_lint: ^2.2.13
  easy_localization: ^3.0.7 # upgrade when openapi intl dependency is updated

# Flutter launcher icon configuration
flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon/temppi_1024.png"
  min_sdk_android: 21

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/translations/
